### PR TITLE
Keep original navbar status after light -> dark -> light

### LINKED ISSUE #268: bs4Dash bug when switch from light to dark to light mode #11
Hi,
I was trying to made a customized bs4Dash using `{fresh}` package but I have some problems. Here's a reproducible example.

```
mytheme = create_theme(

  bs4dash_status(primary = "#2aaae2", light = "#2aaae2"),
  
  bs4dash_sidebar_light(
    bg = "#2c2f76", #sfondo sidebar
    color = "#FFF", #colore testo
    hover_color = "#2aaae2", #colore testo quando evidenziato
    submenu_bg = "#2c2f76", 
    submenu_color = "#FFF", 
    submenu_hover_color = "#2aaae2"
  ),
  
  bs4dash_layout(main_bg = "#FFF"),
  
  bs4dash_vars(
    navbar_light_color = "#2c2f76", #colore icone navbar 
    navbar_light_active_color = "#FFF",
    navbar_light_hover_color = "#FFF"
  )
)

library(shiny)
library(bs4Dash)
library(fresh)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = bs4DashNavbar(
      skin = "light", status = "primary",
      title = dashboardBrand("ShinyDash", color = "primary"),
      
      rightUi = tags$li(class = "dropdown", actionButton(inputId  = "jumptohome", label =NULL, icon = icon("home"),status = "primary")) 
    ),
    
    sidebar = dashboardSidebar(
      skin = "light", 
      inputId = "sidebarState",
      bs4Dash::sidebarUserPanel(name = "nome"),
      
      bs4Dash::sidebarMenu(
        id = "sidebarmenu",
        bs4Dash::menuItem("Home", tabName = "home", icon = icon("home")),
        bs4Dash::menuItem("Cytotoxicity", tabName = "cytotab",icon = icon("file-import")),
        bs4Dash::menuItem("D1", tabName = "d1tab", icon = icon("table"),
                          bs4Dash::menuSubItem("guarda", tabName = "wow")
        )
        
      )
      
      
    ),
    controlbar = dashboardControlbar(),
    footer = dashboardFooter(),
    body = bs4Dash::dashboardBody(
      fresh::use_theme(mytheme),
      tabItems(
        tabItem(tabName = "home",h1(strong("Welcome to ShinyDash!"))),
        tabItem(tabName = "cytotab"),
        tabItem(tabName = "d1tab"),
        tabItem(tabName = "wow", h4("ok")))
    )
  ),
  server = function(input, output) {}
)
```
1. If you try to run the code at the first the navbar is light blue as it should be, but if you change to dark mode and then again to light mode, the navbar becomes white even if in bs4dash_status() I specified that the light color should be that light blue.

Screenshot (150)

Screenshot (151)

2. I want to add a home button in the navbar that has the same behaviour and colors of the switch button and the controllbar button (so like just an icon without the button around and the icon should be dark blue when not triggered, and white when hover or click). I tried some combinations even with different packages but without any luck.

I think my problem is both with `{fresh}` package and with `{bs4Dash}` so I posted the issue also here [https://github.com/dreamRs/fresh/issues/11](https://github.com/dreamRs/fresh/issues/11)

### PR DESCRIPTION
**Pull request by etiennebacher**
This PR is related to #268: when there is a `status` specified for the navbar, switching from "light" to "dark" to "light" again makes the navbar white, forgetting the original `status`.

Example:
```r
library(shiny)
library(bs4Dash)

shinyApp(
  ui = dashboardPage(
    title = "Basic Dashboard",
    header = bs4DashNavbar(
      skin = "light", status = "indigo"
    ),
    sidebar = dashboardSidebar(
      skin = "light"
    ),
    controlbar = dashboardControlbar(),
    footer = dashboardFooter(),
    body = bs4Dash::dashboardBody()
  ),
  server = function(input, output) {}
)
```
Close #268

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
I realised this is actually breaking the switch between light and dark. The navbar ends with class dark in the light mode.
Screenshot 2022-05-05 at 09 20 17

**Comment by etiennebacher** [comment]
@DivadNojnarg Sorry about that, I didn't check when I did this PR. I can't look at that in the next few days but I will try to fix it later

**Comment by DivadNojnarg** [comment]
I added some extra logic:

```js
// get any selected navbar skin in the navbar themer
      var newNavbarColor;
      // If there is not themer, we keep the navbar current color.
      // Otherwise, we replace it by the new color.
      if ($('.navbar-themer-chip').length > 0) {
        $('.navbar-themer-chip').filter(function () {
          if ($(this).css('border-style') === 'solid') {
            newNavbarColor = 'navbar-' +
              $(this)
                .attr('class')
                .split('elevation-2')[0]
                .trim()
                .replace('bg-', '');
          }
        });
      } else {
        newNavbarColor = getNavbarColor();
      }
```

If there is a themer widget, we ignore the current navbar color and update with the new color. If there is no themer, we capture the current color like you did. 

Also there was a missing piece, which I put earlier in the code. This is to make sure the navbar get the correct class based on the selected color. For instance indigo will always be compatible with navbar-dark to get nicer contrast. Inversely, orange will be always with light. In practice, most of the adminLTE colors will have white text, no matter the selected skin:

```js
if (getNavbarColor() !== undefined) {
    updateNavbarTheme(getNavbarColor()); 
  }
```

**Comment by etiennebacher** [comment]
Great!

**Comment by veer0318** [comment]
Hi, this fix:
`if (getNavbarColor() !== undefined) {
    updateNavbarTheme(getNavbarColor()); 
  }`

has yet to be committed, right? So the bug is still open like in issue #293 , right? 

I have this issue with the latest version of the code in the master branch.

**Comment by DivadNojnarg** [comment]
It is a bit more complex. The code I pushed does not work for all cases. There is a missing case I have to consider.

**Comment by DivadNojnarg** [comment]
@veer0318 : just pushed some code to fix it in dev.

**Comment by veer0318** [comment]
You, Sir, are a hero! Thanks, just confirmed that it works here. I'll await the push into the main branch for use in my production dashboards.

**Comment by ApexHeel** [comment]
Any update on when this will be pushed to production?

**Pull request merged**
